name: Arclapain GitHub Readme YouTube Cards
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCcXLspJdUMq5E8-jU0CXuNA
          lang: en
          comment_tag_name: ARCLAPAIN-YOUTUBE-CARDS
          background_color: "#101010"
          title_color: "#FBFBFD"
          stats_color: "#2196f3"
          theme_context_light: '{ "background_color": "#101010", "title_color": "#FBFBFD", "stats_color": "#2196f3" }'
          theme_context_dark: '{ "background_color": "#101010", "title_color": "#FBFBFD", "stats_color": "#2196f3" }'